### ISSUE TITLE
PHP Fatal error accessing to a report detail (ex. report from google.com)

### ISSUE THREAD

**Issue by ciitelecom** [techsneeze/dmarcts-report-viewer#48]
I succeeded to install your solution on my linux station.
I configured NGINX and PHP-FPM 7.2.
I imported my existing DMARC reports (about 1500) with the perl script from the other github project "dmarcts-report-parser".
This part is good.
I can view the reports in the web interface.
But when I want to click on one report to get detail I have this error:

`
2021/01/15 11:08:02 [error] 11445#11445: *26 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'DOMDocument' not found in /var/www/html/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php:144
Stack trace:
#0 /var/www/html/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php(54): formatXML('<?xml version="...')
#1 /var/www/html/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php(239): tmpl_reportData(1490, Array, 1)
#2 {main}
  thrown in /var/www/html/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php on line 144" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /dmarcts-report-viewer/dmarcts-report-viewer-report-data.php?report=1490&hostlookup=1&p=2021-01 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost", referrer: "http://localhost/dmarcts-report-viewer/dmarcts-report-viewer.php"
`

**Comment by ciitelecom** [comment]
Sorry.... I found the reason of this problem.
I had to install the package "php-dom" : apt install php-dom
