### ISSUE TITLE
'DOMDocument' not found 

### ISSUE THREAD

**Issue by wioxjk** [techsneeze/dmarcts-report-viewer#85]
Just installed dmarcts-report-parser, and it seems like there is some classes that is missing:

`[Mon Sep 19 11:22:47.678382 2022] [php7:error] [pid 64682] [client 172.31.20.135:58211] PHP Fatal error: Uncaught Error: Class 'DOMDocument' not found in /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php:210\nStack trace:\n#0 /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php(59): formatXML()\n#1 /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php(366): tmpl_reportData()\n#2 {main}\n thrown in /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php on line 210, referer: http://dmarc-webui.xxx.se/`

FYI - I cloned down the GIT-repo, and not the release

**Comment by wioxjk** [comment]
`Fatal error: Uncaught Error: Class 'DOMDocument' not found in /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php:210 Stack trace: #0 /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php(59): formatXML() #1 /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php(366): tmpl_reportData() #2 {main} thrown in /srv/dmarcts-report-viewer/dmarcts-report-viewer-report-data.php on line 210`

**Comment by wioxjk** [comment]
Nevermind, I forgot to install php-xml.
