### ISSUE TITLE
Error when XML is blank (parser's $maxsize_xml)

### ISSUE THREAD

**Issue by 2called-chaos** [techsneeze/dmarcts-report-viewer#86]
When a report isn't being stored in the DB (due to $maxsize_xml)

> dmarcts-report-parser.pl: google.com: 3694144787112198549: Skipping storage of large XML (75036 bytes) as defined in config file.

I am unable to access it in the viewer, the following error is displayed

```
Fatal error: Uncaught ValueError: DOMDocument::loadXML(): Argument #1 ($source) must not be empty 
in /var/www/viewer/dmarcts-report-viewer-report-data.php:213
Stack trace:
  #0 /var/www/viewer/dmarcts-report-viewer-report-data.php(213): DOMDocument->loadXML()
  #1 /var/www/viewer/dmarcts-report-viewer-report-data.php(59): formatXML()
  #2 /var/www/viewer/dmarcts-report-viewer-report-data.php(366): tmpl_reportData()
  #3 {main} thrown in /var/www/viewer/dmarcts-report-viewer-report-data.php on line 213
```

**Comment by techsneeze** [comment]
I haven't been able to replicate this
