### ISSUE TITLE
report page crash on loading large xml

### ISSUE THREAD

**Issue by spadazza** [techsneeze/dmarcts-report-viewer#91]
When i navigate on the dmarc report viewer, if I access a report with a large number of records, the page throws this php error :

Fatal error: Uncaught ValueError: DOMDocument::loadXML(): Argument #1 ($source) must not be empty in /var/www/viewer/dmarcts-report-viewer-report-data.php:213 Stack trace: #0 /var/www/viewer/dmarcts-report-viewer-report-data.php(213): DOMDocument->loadXML() #1 /var/www/viewer/dmarcts-report-viewer-report-data.php(59): formatXML() #2 /var/www/viewer/dmarcts-report-viewer-report-data.php(366): tmpl_reportData() #3 {main} thrown in /var/www/viewer/dmarcts-report-viewer-report-data.php on line 213

**Comment by jmturner** [comment]
Hi. Any updates on this one?

**Comment by ChucklesTheBeard** [comment]
This error means the xml is missing for that report.

If you're using [dmarcts-report-parser](https://github.com/techsneeze/dmarcts-report-parser) increase the maximum xml size. Default is 50kB.
